StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{62CE126A60074D50}" {
   Id "LLA-Faction_Desc"
   Target_en_us "Lionheart Liberation Army"
   Modified 1657680350
   Author "claud"
   LastChanged "claud"
  }
  CustomStringTableItem "{62CE126A5E2B1B1B}" {
   Id "LLA-Faction_Short"
   Target_en_us "LLA"
   Modified 1657680354
   Author "claud"
   LastChanged "claud"
  }
 }
}